version: '3.9'
services:
  node-api:
    restart: always
    build: ./server/
    ports:
      - 8000:8000
    volumes:
      - ./server:/api
  node-client:
    restart: always
    build: ./client/
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
  mongodb:
    image: "mongo:alpine"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
